### PR TITLE
OSX Yosemite Fixes

### PR DESCRIPTION
**Pull request by thshdw**
Forked from @pthrasher
Cherry picked jbowes@211119c to get anchor support. Per @brianmay removed the check for
ESTABLISHED:ESTABLISHED. These changes prevent [Errno 42] Protocol not available.

### CODE REVIEW

**Comment by thshdw** [comment]
@brianmay
I took your advice from our [conversation](https://github.com/sshuttle/sshuttle/pull/3) and removed the `ESTABLISHED:ESTABLISHED` check. To get the destination IP im doing a regex match based on the peer ip. Perhaps not the best way to go about it but its working for me. I no longer receive the `socket.error [Errno 42] Protocol not available` messages. 

```
def original_dst(sock, method):
    if method == "pf":
        try:
            peer = sock.getpeername()

            output = ssubprocess.Popen(["sudo", "-n", "/sbin/pfctl", "-s", "state"],
             stdout=ssubprocess.PIPE,
                     stderr=ssubprocess.PIPE).communicate()[0]

            peer_ip_port = "%s:%s" % (peer[0], peer[1])
            match = re.search('(?<=%s -> )\S*'%(peer_ip_port), output)
            if match is not None:
                dst = match.group().split(":")
                return(dst[0], dst[1])
            else:
                return(peer[0], peer[1])
        except socket.error, e:
            if eargs[0] == errno.ENOPROTOOPT:
                return sock.getsockname()
            raise
    else:
        try:
            SO_ORIGINAL_DST = 80
            SOCKADDR_MIN = 16
            sockaddr_in = sock.getsockopt(socket.SOL_IP,
                                      SO_ORIGINAL_DST, SOCKADDR_MIN)
            (proto, port, a, b, c, d) = struct.unpack('!HHBBBB', sockaddr_in[:8])
            assert(socket.htons(proto) == socket.AF_INET)
            ip = '%d.%d.%d.%d' % (a, b, c, d)
            return (ip, port)
        except socket.error, e:
            if e.args[0] == errno.ENOPROTOOPT:
                return sock.getsockname()
            raise
```

**Comment by thshdw** [comment]
@tbertelsen and @uraimo could you try sshuttle branch [OSX-yosemite-changes](https://github.com/thshdw/sshuttle/tree/OSX-yosemite-changes) I'm no longer getting: `"socket.error: [Errno 42] Protocol not available".`

**Comment by uraimo** [comment]
Testing right now, i'll report back in a few hours.

**Comment by tbertelsen** [comment]
The functionality is broken in your branch. No connections seem to be intercepted.

Below is the entirety of the output. Nothing is printed when I use the network. This is opposed to pthrasher/main, which prints tons of lines.

```
~/git/sshuttle/thshdw/sshuttle/src
09:49:48:(OSX-yosemite-changes)$ ./sshuttle -r porus 0/0 -vv
Starting sshuttle proxy.
recvmsg socket_ext support enabled.
UDP support requires tproxy; disabling UDP.
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
firewall manager ready method pf.
c : connecting to server...
c : executing: ['ssh', 'porus', '--', 'P=python2; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; skip_imports=1; verbosity=2; exec compile(sys.stdin.read(770), "assembler.py", "exec")\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'cmdline_options.py' (41 bytes)
server: assembling 'helpers.py' (786 bytes)
server: assembling 'ssubprocess.py' (13703 bytes)
server: assembling 'ssnet.py' (5467 bytes)
server: assembling 'hostwatch.py' (2242 bytes)
server: assembling 'server.py' (3026 bytes)
 s: latency control setting = True
 s: available routes:
 s:   2/10.128.7.0/24
 s:   2/169.254.0.0/16
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=33 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=40/0)
 s:   Ready: 1 r=[] w=[5] x=[]
c : connected.
 s: mux wrote: 15/15
Connected.
 s: mux wrote: 41/41
c : Waiting: 2 r=[5, 8] w=[8] x=[] (fullness=7/0)
c :   Ready: 2 r=[8] w=[8] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=33
firewall manager: starting transproxy.
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=40/0)
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[5, 8] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=40)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
c :   Ready: 2 r=[8] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 2 r=[5, 8] w=[] x=[] (fullness=0/0)
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
```

**Comment by uraimo** [comment]
Oops, didn't switch to OSX-yosemite-changes, and as @tbertelsen said, no traffic at all on the tunnel with these patches.

**Comment by uraimo** [comment]
The commit that introduced anchor support 271fe57 breaks it for me on Yosemite 10.10.2 (noticed the bad merge and fixed it), after that commit traffic is not forwarded anymore to sshuttle, and the refactoring you did with 043c41d (removing stdin and going back to a file based configuration) doesn't remove the issue.
After reading the original discussion, looking at the code in 043c41d and checking the pfctl man i don't see anything wrong atm...

I've reverted that change, opened a PR thshdw/sshuttle#2 and i'm testing that version to verify if the main issue related to the "Protocol not available" error is fixed. IMHO, the introduction of the anchor option can wait after the disconnection issue is fixed, when we have something working to start from.

**Comment by thshdw** [comment]
@tbertelsen and @uraimo Thanks for the testing and feedback. I have the 10.10.3 beta and its working for me. I'll have to do some testing on 10.10.2 to see what is going on.

**Comment by thshdw** [comment]
@tbertelsen and @uraimo 
Perhaps that pfctl is a bit messed up from previous sshuttle runs which continually enable then disable pfctl.

On your systems try running the following commands:

```
sudo pfctl -e
sudo pfctl -f /etc/pf.conf
sudo pfctl -d
```

this will enable pfctl flush the rules then disable it. Then try sshuttle again to see if the anchors are working for you. I do notice that sometimes on the first run it takes about 30 or 40 seconds for it to start.

Here is some proof that its working for me...

after I start it I see lots of feedback in the terminal session that traffic is flowing 

```
c :   Ready: 20 r=[20, 22, 24] w=[9] x=[]
c : mux wrote: 235/235
c :  > channel=21 cmd=TCP_DATA len=2048 (fullness=18029)
c :  > channel=21 cmd=TCP_DATA len=235 (fullness=20077)
c :  > channel=33 cmd=TCP_DATA len=2048 (fullness=20312)
c :  > channel=33 cmd=TCP_DATA len=231 (fullness=22360)
c :  > channel=35 cmd=TCP_DATA len=2048 (fullness=22591)
c :  > channel=35 cmd=TCP_DATA len=234 (fullness=24639)
c : mux wrote: 2056/2056
c : Waiting: 20 r=[5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25] w=[9] x=[] (fullness=24873/0)
```

Here is a screen shot of me browsing jira (which is inside the remote network)

screen shot 2015-03-13 at 10 13 50 am

here is the output of `sudo pfctl -s Anchors -v` this prints a list of the current anchors

```
Last login: Fri Mar 13 09:57:34 on ttys000
thshdw-mac-book:src thshdw$ sudo pfctl -s Anchors -v
No ALTQ support in kernel
ALTQ related functions disabled
  com.apple
  com.apple/200.AirDrop
  com.apple/250.ApplicationFirewall
  com.apple/sshuttle
thshdw-mac-book:src thshdw$
```

here is the output of `sudo pfctl -a com.apple/sshuttle -s rules` this shows the rules for anchor `sshuttle`

```
Last login: Fri Mar 13 10:03:11 on ttys001
thshdw-mac-book:~ thshdw$ sudo pfctl -a com.apple/sshuttle -s rules 
No ALTQ support in kernel
ALTQ related functions disabled
pass out route-to lo0 inet proto tcp all flags S/SA keep state
pass out route-to lo0 inet proto udp from any to 172.20.10.1 port = 53 keep state
pass out quick inet proto tcp from any to 127.0.0.0/8 flags S/SA keep state
thshdw-mac-book:~ thshdw$
```

here is the output of `sudo pfctl -a com.apple/sshuttle -s states` which lists the anchor's states

```
Last login: Fri Mar 13 10:04:35 on ttys003
thshdw-mac-book:~ thshdw$ sudo pfctl -a com.apple/sshuttle -s states
No ALTQ support in kernel
ALTQ related functions disabled
ALL tcp 172.20.10.7:51457 -> 172.20.10.1:53       FIN_WAIT_2:ESTABLISHED
ALL tcp 127.0.0.1:12300 <- 172.20.10.1:53 <- 172.20.10.7:51457       ESTABLISHED:FIN_WAIT_2
ALL tcp 172.20.10.7:49868 -> 172.20.10.1:53       FIN_WAIT_2:ESTABLISHED
ALL tcp 127.0.0.1:12300 <- 172.20.10.1:53 <- 172.20.10.7:49868       ESTABLISHED:FIN_WAIT_2
ALL tcp 172.20.10.7:49293 -> 10.40.124.50:389       FIN_WAIT_2:FIN_WAIT_2
ALL tcp 172.20.10.7:49294 -> 10.40.124.50:389       FIN_WAIT_2:FIN_WAIT_2
ALL tcp 127.0.0.1:12300 <- 10.40.124.50:389 <- 172.20.10.7:49293       FIN_WAIT_2:FIN_WAIT_2
ALL tcp 127.0.0.1:12300 <- 10.40.124.50:389 <- 172.20.10.7:49294       FIN_WAIT_2:FIN_WAIT_2
ALL tcp 172.20.10.7:49295 -> 10.40.124.50:389       FIN_WAIT_2:FIN_WAIT_2
ALL tcp 127.0.0.1:12300 <- 10.40.124.50:389 <- 172.20.10.7:49295       FIN_WAIT_2:FIN_WAIT_2
ALL tcp 172.20.10.7:49296 -> 10.40.124.50:389       FIN_WAIT_2:FIN_WAIT_2
ALL tcp 127.0.0.1:12300 <- 10.40.124.50:389 <- 172.20.10.7:49296       FIN_WAIT_2:FIN_WAIT_2
ALL tcp 172.20.10.7:49297 -> 10.40.124.50:389       ESTABLISHED:ESTABLISHED
ALL tcp 127.0.0.1:12300 <- 10.40.124.50:389 <- 172.20.10.7:49297       ESTABLISHED:ESTABLISHED
thshdw-mac-book:~ thshdw$
```

here is the anchor list after stopping sshuttle 

```
thshdw-mac-book:src thshdw$ sudo pfctl -s Anchors -v
No ALTQ support in kernel
ALTQ related functions disabled
  com.apple
  com.apple/200.AirDrop
  com.apple/250.ApplicationFirewall
thshdw-mac-book:src thshdw$
```

notice the sshuttle anchor is gone.

**Comment by uraimo** [comment]
Ok, verified that after flushing the rules it actually starts working! I've also verified that the anchor is applied when sshuttle is started, that dns rules are there when running and that the anchor is cleanly removed on exit.

The only weird thing i'm seeing is the connection failing with the common "broken pipe" error after a few minutes, but it could REALLY be an issue caused by my crappy DSL connection, unrelated to sshuttle:

```
Write failed: Broken pipe
client: fatal: server died with error code 255
```

I'll test it more tomorrow, btw.

**Comment by thshdw** [comment]
@uraimo Thanks for the confirmation!

Regarding `server died with error code 255` the threads [here](https://groups.google.com/forum/#!topic/sshuttle/P7Y2DPWXOW4) and [here](https://groups.google.com/forum/#!topic/sshuttle/fsTCteXbLQA) on the sshuttle discussion groups indicate that this error is related to the ssh server or the connection.

Keep us updated with tomorrows results  :smiley:

**Comment by uraimo** [comment]
After 4 hours or so of additional testing it seems quite stable. :+1:

**Comment by thshdw** [comment]
@uraimo Thank you for the update!

**Pull request closed without merging**
